### ISSUE TITLE
Provide requirements for the project

### ISSUE THREAD

**Issue by MW3000** [TUB-NLP-OpenData/usability_research_data#1]
Add a description of the dependencies/requirements for this project. One very easy way would be to use requirements.txt
https://pip.pypa.io/en/latest/user_guide/#requirements-files

**Comment by vwoloszyn** [comment]
Very good idea! @andrewedrictristan can you generate it?

**Comment by andrewedrictristan** [comment]
Of course. I will do it after office.




________________________________
Von: Vinicius Woloszyn <notifications@github.com>
Gesendet: Mittwoch, 16. September 2020 13:15
An: TUB-NLP-OpenData/usability_research_data <usability_research_data@noreply.github.com>
Cc: andrewtristan <andrew_tristan23@outlook.com>; Mention <mention@noreply.github.com>
Betreff: Re: [TUB-NLP-OpenData/usability_research_data] Provide requirements for the project (#1)


Very good idea! @andrewedrictristan<https://github.com/andrewedrictristan> can you generate it?

**Comment by vwoloszyn** [comment]
@MW3000 it's done! (I have also created setup.py) you can install using the following command: pip install git+https://github.com/TUB-NLP-OpenData/usability_research_data all the best ;)
