### ISSUE TITLE
Plan A -  This tool should have more support in transformation of data type

### ISSUE THREAD

**Issue by andrewedrictristan** [TUB-NLP-OpenData/usability_research_data#11]
This aims to store the data in a variable, where this variable will be used to be
cleaned or to be analyzed. E.g:
`dataSetVar = bopi.repository(“xx/xx”).datasets().get(“filename.csv”).toCSV()`

or 

`dataSetVar = bopi.repository(“xx/xx”).datasets().get(“filename.csv”).toJson()`

**Comment by vwoloszyn** [comment]
Fixed it!

bopi.repository("11303/10989.2").datasets().get('Xb.csv').to_json("./test.csv")

instead .toCSV and .toCSV(), let's use pandas' taxinomy e.g. .to_json() and .to_csv()

;)
