### ISSUE TITLE
Plan A - fix the datasets function

### ISSUE THREAD

**Issue by andrewedrictristan** [TUB-NLP-OpenData/usability_research_data#8]
Problem:
- The user doesn’t know the content of the object’s dataset such as the  Pdf or CSV data in one repository.
E.g: 
`bopi.repository("11303/11457").datasets()` just has object element output without the clear Filename or Datatype

Output example:
[<bopi.utils.Dataset at 0x7efe06177898>,
 <bopi.utils.Dataset at 0x7efe061778d0>,
 <bopi.utils.Dataset at 0x7efe06177908>,
 <bopi.utils.Dataset at 0x7efe06177940>,
 <bopi.utils.Dataset at 0x7efe06177978>,
 <bopi.utils.Dataset at 0x7efe061779b0>]

**Suggestion:**
` bopi.repository(“xx/xx”).datasets()  `  To extract all CSV or PDF filenames in array list.
The array list that starts from 1, e.g:

1. datasetA.csv
2. datasetB.csv
3. datasetC.csv
4. dataToRead.pdf

**Comment by vwoloszyn** [comment]
done ;)
